---
title: "Behind Bars and Beyond: Investigating Socioeconomic Drivers of Incarceration Rates in the United States"
subtitle: "A comparative analysis of global trends and America's mass incarceration crisis."
author: 
  - Abbass Sleiman
thanks: "Code and data are available at: [https://github.com/AbbassSleiman/US-Middle-Class](https://github.com/AbbassSleiman/US-Middle-Class)."
date: today
date-format: long
format: 
  pdf: 
    include-in-header: 
      text: |
        \usepackage{lscape}
        \newcommand{\blandscape}{\begin{landscape}}
        \newcommand{\elandscape}{\end{landscape}}
    documentclass: article
    geometry: margin = 1.2in
    abstract: "Over the past five decades, the United States has witnessed a decline in the percentage of adults residing in middle-class households, alongside escalating concerns about housing affordability. This study aims to assess the impact of rising costs on the living standards of middle and lower-income households, recognizing them as the most affected demographic by these economic shifts. Utilizing data from [...], we analyze changes in income distribution and evaluate the influence of economic policy changes, including interest rates and taxation, on the standards of living of these individuals. Additionally, we explore how individual-level characteristics intersect with these policies to address how best to pursue the goal of economic equity across individuals of all backgrounds. We find that [...]."
    number-sections: true
output: 
  bookdown::pdf_document2
toc: true
bibliography: references.bib
---

```{r}
#| include: false
#| warning: false
#| message: false

library(tidyverse)
```


# Introduction

In recent decades, the United States has grappled with a consistent rise in its prison population, becoming infamous for having one of the highest incarceration rates in the world. Leading the world with nearly 2 million individuals in prisons and jails in 2022, the US is faced with what, at first glance, appears to be a "uniquely American problem" [@citeUSincarceration]. This phenomenon has sparked widespread concern and debate over how best to address this issue. Central to these discussions is the question of what underlying factors have contributed to this circumstance, in turn necessitating an exploration of the socioeconomic drivers of incarceration rates in the United States.

Incarceration refers to the state of being confined in prison as punishment for criminal offences [@citeIncarcerationRate], and in examining the United States' prison dilemma, it becomes clear that the crux of the problem is not easily reducible to simple explanations. Instead, it is a complex issue influenced by a multitude of factors including cultural dynamics and socioeconomic conditions. Thus, in an attempt to unravel the intricacies of these factors, this paper seeks to conduct a comparative analysis of global trends in education, unemployment, crime, and poverty rates as independent factors influencing a nation's incarceration. However, recognizing that the total number of incarcerations is heavily dependent on population size, this paper focuses on nations' incarceration rates as the estimand, defined to be the number of incarcerated individuals per 100,000 in a given population [@citeIncarcerationRate], which serves as a better metric for measuring the extent of imprisonment within a society. By exploring the impact of these factors on incarceration rates, we aim to better understand the primary forces behind the United States' high incarceration rate and overall number of individuals incarcerated. This understanding will help inform policy-making decisions aimed at addressing the issue effectively.

This paper utilizes various datasets from the World Population Review, in particular it utilizes their datasets on "Incarceration Rates by Country 2024", "Poverty Rate by Country 2024", "Education Rankings by Country 2024", "Unemployment by Country 2024", and "Crime Rate by Country 2024". By conducting statistical analyses with the aforementioned data, this paper finds evidence to suggest that [...]

The remainder of this paper is structured as follows. @sec-data discusses the raw data, cleaning process, variables of interest, and offers visual representations of the data through tabular and graphical representations of the observations. @sec-model introduces and justifies the Bayesian linear regression model used in the analysis of the data in predicting the relationship between the aforementioned independent variables and a nation's incarceration rate. @sec-results deals with analyzing the trends and correlations showcased by the model in more detail. @sec-discussion discusses the real-world implications of the results uncovered in the prior sections, and finally @sec-limitations discusses the limitations and weaknesses of the analysis conducted, as well as the next steps that could be taken to improve the overall reliability of the paper.

# Data {#sec-data}

This paper utilizes 5 datasets, all provided by the World Population Review and each providing information on one of the 5 factors involved in this study. @sec-incarceration-data features the most recently available information on incarcerations and incarceration rates of 219 countries and territories as of 2024. @sec-poverty-data features the data on the poverty rates of 164 nations. @sec-crime-data .

## Incarceration Rate Dataset {#sec-incarceration-data}

## Poverty Rate Dataset {#sec-poverty-data}

## Crime Rate Dataset {#sec-crime-data}

## Unemployment Rate Dataset {#sec-unemployment-data}

## Education Ranking Dataset {#sec-education-data}



# Model {#sec-model}


## Model set-up



### Model justification



# Results {#sec-results}



# Discussion {#sec-discussion}

## First discussion point {#sec-first-point}

## Second discussion point

## Third discussion point


# Weaknesses and next steps {#sec-limitations}

\newpage

\appendix

# Appendix {-}


# Additional data details

# Model details {#sec-model-details}

## Posterior predictive check



\newpage


# References


